<?php

namespace Acme\DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * @return \Doctrine\ORM\Query
     */
    public function searchQuery()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('C');
        $qb->from('AcmeDemoBundle:Category', 'C');

        return $qb->getQuery();
    }

}
